version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      APP_DEBUG: 'true'
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
    # command: /bin/sh -c "php artisan serve --host 0.0.0.0 --port=8000"

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todolist
    volumes:
      - todolist-postgres-volume:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build-stage
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend
    command: /bin/sh -c "npm run serve --host=0.0.0.0 --port=8080"

volumes:
  todolist-postgres-volume: 
